#ifndef TGBOT_TGBOT_H
#define TGBOT_TGBOT_H

#include "Api.h"
#include "Bot.h"
#include "EventBroadcaster.h"
#include "EventHandler.h"
#include "TgException.h"
#include "TgTypeParser.h"
#include "net/BoostHttpOnlySslClient.h"
#include "net/CurlHttpClient.h"
#include "net/HttpClient.h"
#include "net/HttpParser.h"
#include "net/HttpReqArg.h"
#include "net/HttpServer.h"
#include "net/TgLongPoll.h"
#include "net/TgWebhookLocalServer.h"
#include "net/TgWebhookServer.h"
#include "net/TgWebhookTcpServer.h"
#include "net/Url.h"
#include "tgbot.h"
#include "tools/FileTools.h"
#include "tools/StringTools.h"
#include "Animation.h"
#include "Audio.h"
#include "CallbackGame.h"
#include "CallbackQuery.h"
#include "Chat.h"
#include "ChatMember.h"
#include "ChatPhoto.h"
#include "ChosenInlineResult.h"
#include "Contact.h"
#include "Document.h"
#include "File.h"
#include "ForceReply.h"
#include "Game.h"
#include "GameHighScore.h"
#include "GenericReply.h"
#include "InlineKeyboardButton.h"
#include "InlineKeyboardMarkup.h"
#include "InlineQuery.h"
#include "InlineQueryResult.h"
#include "InlineQueryResultArticle.h"
#include "InlineQueryResultAudio.h"
#include "InlineQueryResultCachedAudio.h"
#include "InlineQueryResultCachedDocument.h"
#include "InlineQueryResultCachedGif.h"
#include "InlineQueryResultCachedMpeg4Gif.h"
#include "InlineQueryResultCachedPhoto.h"
#include "InlineQueryResultCachedSticker.h"
#include "InlineQueryResultCachedVideo.h"
#include "InlineQueryResultCachedVoice.h"
#include "InlineQueryResultContact.h"
#include "InlineQueryResultDocument.h"
#include "InlineQueryResultGame.h"
#include "InlineQueryResultGif.h"
#include "InlineQueryResultLocation.h"
#include "InlineQueryResultMpeg4Gif.h"
#include "InlineQueryResultPhoto.h"
#include "InlineQueryResultVenue.h"
#include "InlineQueryResultVideo.h"
#include "InlineQueryResultVoice.h"
#include "InputContactMessageContent.h"
#include "InputFile.h"
#include "InputLocationMessageContent.h"
#include "InputMedia.h"
#include "InputMediaPhoto.h"
#include "InputMediaVideo.h"
#include "InputMessageContent.h"
#include "InputTextMessageContent.h"
#include "InputVenueMessageContent.h"
#include "Invoice.h"
#include "KeyboardButton.h"
#include "LabeledPrice.h"
#include "Location.h"
#include "MaskPosition.h"
#include "Message.h"
#include "MessageEntity.h"
#include "OrderInfo.h"
#include "PhotoSize.h"
#include "PreCheckoutQuery.h"
#include "ReplyKeyboardMarkup.h"
#include "ReplyKeyboardRemove.h"
#include "ResponseParameters.h"
#include "ShippingAddress.h"
#include "ShippingOption.h"
#include "ShippingQuery.h"
#include "Sticker.h"
#include "StickerSet.h"
#include "SuccessfulPayment.h"
#include "Update.h"
#include "User.h"
#include "UserProfilePhotos.h"
#include "Venue.h"
#include "Video.h"
#include "VideoNote.h"
#include "Voice.h"
#include "WebhookInfo.h"
#include "BotCommand.h"


/**
 * @defgroup general
 * @defgroup types
 * @defgroup net
 * @defgroup tools
 *
 * @mainpage
 * [Go to GitHub](https://github.com/reo7sp/tgbot-cpp)
 *
 */

#endif //TGBOT_TGBOT_H
