#ifndef TGBOT_TGBOT_H
#define TGBOT_TGBOT_H

#include "Api.h"
#include "Bot.h"
#include "EventBroadcaster.h"
#include "EventHandler.h"
#include "TgException.h"
#include "TgTypeParser.h"
#include "net/BoostHttpOnlySslClient.h"
#include "net/CurlHttpClient.h"
#include "net/HttpClient.h"
#include "net/HttpParser.h"
#include "net/HttpReqArg.h"
#include "net/HttpServer.h"
#include "net/TgLongPoll.h"
#include "net/TgWebhookLocalServer.h"
#include "net/TgWebhookServer.h"
#include "net/TgWebhookTcpServer.h"
#include "net/Url.h"
#include "tgbot.h"
#include "tools/FileTools.h"
#include "tools/StringTools.h"
#include "types/Animation.h"
#include "types/Audio.h"
#include "types/CallbackGame.h"
#include "types/CallbackQuery.h"
#include "types/Chat.h"
#include "types/ChatMember.h"
#include "types/ChatPhoto.h"
#include "types/ChosenInlineResult.h"
#include "types/Contact.h"
#include "types/Document.h"
#include "types/File.h"
#include "types/ForceReply.h"
#include "types/Game.h"
#include "types/GameHighScore.h"
#include "types/GenericReply.h"
#include "types/InlineKeyboardButton.h"
#include "types/InlineKeyboardMarkup.h"
#include "types/InlineQuery.h"
#include "types/InlineQueryResult.h"
#include "types/InlineQueryResultArticle.h"
#include "types/InlineQueryResultAudio.h"
#include "types/InlineQueryResultCachedAudio.h"
#include "types/InlineQueryResultCachedDocument.h"
#include "types/InlineQueryResultCachedGif.h"
#include "types/InlineQueryResultCachedMpeg4Gif.h"
#include "types/InlineQueryResultCachedPhoto.h"
#include "types/InlineQueryResultCachedSticker.h"
#include "types/InlineQueryResultCachedVideo.h"
#include "types/InlineQueryResultCachedVoice.h"
#include "types/InlineQueryResultContact.h"
#include "types/InlineQueryResultDocument.h"
#include "types/InlineQueryResultGame.h"
#include "types/InlineQueryResultGif.h"
#include "types/InlineQueryResultLocation.h"
#include "types/InlineQueryResultMpeg4Gif.h"
#include "types/InlineQueryResultPhoto.h"
#include "types/InlineQueryResultVenue.h"
#include "types/InlineQueryResultVideo.h"
#include "types/InlineQueryResultVoice.h"
#include "types/InputContactMessageContent.h"
#include "types/InputFile.h"
#include "types/InputLocationMessageContent.h"
#include "types/InputMedia.h"
#include "types/InputMediaPhoto.h"
#include "types/InputMediaVideo.h"
#include "types/InputMessageContent.h"
#include "types/InputTextMessageContent.h"
#include "types/InputVenueMessageContent.h"
#include "types/Invoice.h"
#include "types/KeyboardButton.h"
#include "types/LabeledPrice.h"
#include "types/Location.h"
#include "types/MaskPosition.h"
#include "types/Message.h"
#include "types/MessageEntity.h"
#include "types/OrderInfo.h"
#include "types/PhotoSize.h"
#include "types/PreCheckoutQuery.h"
#include "types/ReplyKeyboardMarkup.h"
#include "types/ReplyKeyboardRemove.h"
#include "types/ResponseParameters.h"
#include "types/ShippingAddress.h"
#include "types/ShippingOption.h"
#include "types/ShippingQuery.h"
#include "types/Sticker.h"
#include "types/StickerSet.h"
#include "types/SuccessfulPayment.h"
#include "types/Update.h"
#include "types/User.h"
#include "types/UserProfilePhotos.h"
#include "types/Venue.h"
#include "types/Video.h"
#include "types/VideoNote.h"
#include "types/Voice.h"
#include "types/WebhookInfo.h"
#include "types/BotCommand.h"


/**
 * @defgroup general
 * @defgroup types
 * @defgroup net
 * @defgroup tools
 *
 * @mainpage
 * [Go to GitHub](https://github.com/reo7sp/tgbot-cpp)
 *
 */

#endif //TGBOT_TGBOT_H
